name: QuantumFlow Elite Bybit Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
  workflow_dispatch:        # Manual trigger
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    
    env:
      BYBIT_API_KEY: ${{ secrets.BYBIT_API_KEY }}
      BYBIT_API_SECRET: ${{ secrets.BYBIT_API_SECRET }}
      BYBIT_TESTNET_API_KEY: ${{ secrets.BYBIT_TESTNET_API_KEY }}
      BYBIT_TESTNET_API_SECRET: ${{ secrets.BYBIT_TESTNET_API_SECRET }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      USE_TESTNET: ${{ secrets.USE_TESTNET }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create logs directory
      run: mkdir -p logs
        
    - name: Setup timezone
      run: |
        sudo timedatectl set-timezone UTC
        
    - name: Run Bot
      run: |
        echo "Starting QuantumFlow Elite Bot..."
        python github_bot.py
        
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: bot-logs-${{ github.sha }}
        path: logs/
        retention-days: 7
